"""Step 3 of crash integration: assign crashes to segments (buffer method).

Each crash is credited to its SINGLE NEAREST segment within MAX_FT (~200 ft,
per Dumbaugh, Rae & Wunneburger 2011). Nearest-only keeps every crash counted
once, so per-segment counts sum back to the assigned-crash total.

Divided roads: we also search the `merged_away` halves (removed during the
dual-carriageway merge) and credit a hit there to its representative seg_id,
so crashes on either side of a boulevard land on the one analysis segment.

Adds per-segment crash counts to the enriched segment layer (idempotent).
Outputs:
  data/processed/district_c_segments_enriched.gpkg  (+ crash count columns)
  reports/crash_assignment_report.md
"""

from pathlib import Path

import geopandas as gpd
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"
MAX_FT = 200

OWNED = ["n_crash", "n_injury", "n_severe", "n_fatal", "n_ped", "n_bike",
         "n_ped_severe", "n_bike_severe"]

seg = gpd.read_file(PROCESSED / "district_c_segments_enriched.gpkg", layer="segments")
seg = seg.drop(columns=[c for c in OWNED if c in seg.columns])
crashes = gpd.read_file(PROCESSED / "district_c_crashes.gpkg", layer="crashes").to_crs(seg.crs)

# --- build the assignment-target geometry set --------------------------------
# real segments map to themselves; merged-away halves map to their representative
targets = seg[["seg_id", "geometry"]].copy()
targets["target"] = targets["seg_id"]
try:
    away = gpd.read_file(PROCESSED / "district_c_segments_clean.gpkg", layer="merged_away")
    away = away.to_crs(seg.crs)[["rep_seg_id", "geometry"]].rename(columns={"rep_seg_id": "target"})
    away = away[away["target"].isin(set(seg["seg_id"]))]
    targets = pd.concat([targets[["target", "geometry"]], away[["target", "geometry"]]],
                        ignore_index=True)
    print(f"Assignment geometries: {len(seg):,} segments + {len(away):,} merged-away halves")
except Exception as e:
    print(f"(no merged_away layer used: {e})")
targets = gpd.GeoDataFrame(targets, geometry="geometry", crs=seg.crs)

# --- nearest segment within MAX_FT -------------------------------------------
crashes = crashes.reset_index(drop=True)
crashes["cidx"] = crashes.index
near = gpd.sjoin_nearest(crashes, targets, how="left", max_distance=MAX_FT,
                         distance_col="dist_ft")
near = near.sort_values("dist_ft").drop_duplicates("cidx")  # one segment per crash
assigned = near[near["target"].notna()].copy()
n_assigned, n_total = len(assigned), len(crashes)
print(f"Assigned {n_assigned:,}/{n_total:,} crashes ({100*n_assigned/n_total:.1f}%) "
      f"within {MAX_FT} ft")

# --- aggregate counts per segment --------------------------------------------
a = assigned
counts = pd.DataFrame({
    "n_crash": a.groupby("target").size(),
    "n_injury": a[a["any_injury"]].groupby("target").size(),
    "n_severe": a[a["severe"]].groupby("target").size(),
    "n_fatal": a[a["fatal"]].groupby("target").size(),
    "n_ped": a[a["involves_ped"]].groupby("target").size(),
    "n_bike": a[a["involves_bike"]].groupby("target").size(),
    "n_ped_severe": a[a["involves_ped"] & a["severe"]].groupby("target").size(),
    "n_bike_severe": a[a["involves_bike"] & a["severe"]].groupby("target").size(),
}).fillna(0).astype(int)

seg = seg.merge(counts, left_on="seg_id", right_index=True, how="left")
for c in OWNED:
    seg[c] = seg[c].fillna(0).astype(int)

out = PROCESSED / "district_c_segments_enriched.gpkg"
seg.to_file(out, layer="segments", driver="GPKG")
print(f"Saved crash counts -> {out}")

# --- report -------------------------------------------------------------------
# identity check: per-segment sums must equal assigned totals (counted once)
checks = {
    "n_crash": (seg["n_crash"].sum(), n_assigned),
    "n_severe": (seg["n_severe"].sum(), int(assigned["severe"].sum())),
    "n_ped": (seg["n_ped"].sum(), int(assigned["involves_ped"].sum())),
}
dist = near.loc[near["target"].notna(), "dist_ft"]
top = (seg[seg["name"].notna()].groupby("name")["n_severe"].sum()
       .sort_values(ascending=False).head(12))
unassigned = n_total - n_assigned

report = f"""# Crash Assignment Report (Step 3)

Generated by `src/assign_crashes.py`. Each crash credited to its single nearest
segment within {MAX_FT} ft (Dumbaugh/Rae/Wunneburger buffer); divided-road
halves searched too and credited to the representative segment.

## Assignment
- Crashes assigned: **{n_assigned:,} / {n_total:,} ({100*n_assigned/n_total:.1f}%)**
- Unassigned (> {MAX_FT} ft from any city street): {unassigned:,} — expected
  (freeway/feeder crashes on excluded roads, plus geocoding error).
- Distance to assigned segment (ft): median {dist.median():.0f}, p90 {dist.quantile(.9):.0f}, p99 {dist.quantile(.99):.0f}.

## Count integrity (each crash counted once → sums match)
{chr(10).join(f"- {k}: per-segment sum {s:,} vs assigned total {t:,}  {'OK' if s==t else 'MISMATCH'}" for k,(s,t) in checks.items())}

## Per-segment outcome columns added
`n_crash`, `n_injury`, `n_severe` (K+A — the model outcome), `n_fatal`,
`n_ped`, `n_bike`, `n_ped_severe`, `n_bike_severe`.

- Segments with ≥1 severe crash: {int((seg['n_severe']>0).sum()):,} of {len(seg):,}
  ({100*(seg['n_severe']>0).mean():.1f}%) — most segments have zero, confirming the
  overdispersed/zero-heavy pattern the negative binomial is built for.
- Max severe crashes on one segment: {int(seg['n_severe'].max())}.

## Top corridors by severe crashes (sanity check)

{top.to_string()}

## Notes
- Intersection crashes are credited to the nearest leg (count-preserving). A
  finer intersection-influence assignment is possible later if needed.
- Counts reflect the years currently in data/raw/CRIS/ (2016–2024 + partial
  2026; 2020/2025 pending). Rerun build_crashes.py then assign_crashes.py to
  refresh when those arrive.
"""
REPORTS.mkdir(exist_ok=True)
(REPORTS / "crash_assignment_report.md").write_text(report)
print(report)
