"""Imagery ablation: is the v1-to-v2 gain visual content or coverage geography?

Imagery coverage is not random: sampling targeted arterials and collectors,
so the availability flag itself encodes road class, geography, and activity.
A model could improve from 47% to 49% merely by learning WHERE Mapillary
coverage exists, without any computer-vision output mattering. This audit
(requested by external review, 2026-07-10) separates the two.

Four models, identical district-blocked CV protocol (model_validate):

  A. v1               design + context, no imagery columns
  B. v1 + flags       adds ONLY the availability information: sv_missing and
                      sv_pano_share (the measurement covariates). No CV
                      content. If B ~= v2, the gain was coverage geography.
  C. v2 (full)        adds the extracted visual features (vehicle/person
                      counts, pixel shares) on top of the flags.
  D. observed subset  capture computed only within the 18,133 segments that
                      carry imagery (where the availability flag is constant),
                      v1 vs v2: the cleanest content-only comparison.

Reading rule (set before running): the imagery contribution claim survives
if C exceeds B citywide AND v2 beats v1 within the observed subset. If B
alone reproduces the v2 gain, the paper's imagery claim must be narrowed to
a coverage effect.

Outputs: reports/imagery_ablation_report.md
"""

import warnings
from datetime import date

import geopandas as gpd
import numpy as np
import pandas as pd

import config as cfg
from model_nb import design_matrix, prepare
from model_v2_imagery import sv_design
from model_validate import blocked_oof, capture

REPORTS = cfg.REPORTS
np.random.seed(42)
warnings.filterwarnings("ignore")

GI_MILES, HIN_MILES = 546.0, 589.0
FLAG_COLS = ["sv_missing", "sv_pano_share"]


def main():
    seg = gpd.read_file(cfg.processed("segments_model.gpkg"), layer="segments")
    seg = seg.reset_index(drop=True)
    d = prepare(seg).reset_index(drop=True)
    X1 = design_matrix(d).reset_index(drop=True)
    sv = sv_design(seg, d)

    Xf = pd.concat([X1, sv[FLAG_COLS]], axis=1)
    X2 = pd.concat([X1, sv], axis=1)
    districts = seg["district"].fillna("none")

    print("district-blocked OOF for A (v1), B (v1+flags), C (v2)...")
    mu_a, _ = blocked_oof(d, X1, districts, "A v1")
    mu_b, _ = blocked_oof(d, Xf, districts, "B v1+flags")
    mu_c, _ = blocked_oof(d, X2, districts, "C v2 full")

    length = seg.length_ft.to_numpy()
    base = pd.DataFrame({"length_ft": length, "n_severe": d.n_severe})

    def cap_row(mu, sub=None):
        ok = np.isfinite(mu)
        if sub is not None:
            ok = ok & sub
        s = base[ok]
        c = capture(s, mu[ok] / (s.length_ft / 5280), [GI_MILES, HIN_MILES])
        c["cov"] = float(ok.mean())
        return c

    caps = {
        "A. v1 (design + context, no imagery)": cap_row(mu_a),
        "B. v1 + availability flags only (sv_missing, sv_pano_share)": cap_row(mu_b),
        "C. v2 (flags + extracted visual features)": cap_row(mu_c),
    }

    # D: within the observed-imagery subset (availability constant)
    obs = (sv["sv_missing"].to_numpy() == 0.0)
    sub_mi = length[obs].sum() / 5280
    sub_sev = int(d.n_severe[obs].sum())
    caps_sub = {
        "v1 within imagery subset": cap_row(mu_a, obs),
        "v2 within imagery subset": cap_row(mu_c, obs),
    }

    def pct(x):
        return f"{100 * x:.0f}%"

    rows = "\n".join(f"| {k} | {pct(v[GI_MILES])} | {pct(v[HIN_MILES])} |"
                     for k, v in caps.items())
    rows_sub = "\n".join(f"| {k} | {pct(v[GI_MILES])} | {pct(v[HIN_MILES])} |"
                         for k, v in caps_sub.items())

    report = f"""# Imagery Ablation Report

Generated by `src/audit_imagery_ablation.py`, {date.today()}. Question: does
the v1-to-v2 capture gain come from the computer-vision content of the
photographs, or merely from knowing where Mapillary coverage exists
(availability correlates with road class and activity by construction)?
All rows use the identical district-blocked CV protocol of modeling step 3.

## Citywide capture, out-of-fold ({len(seg):,} segments)

| Model | top 546 mi | top 589 mi |
|---|---|---|
{rows}

B adds ONLY availability information (missing flag, panorama share); C adds
the extracted visual features on top. The C-minus-B gap is the contribution
of visual content; the B-minus-A gap is the contribution of coverage
geography.

## Within the observed-imagery subset ({sub_mi:,.0f} mi, {sub_sev:,} severe crashes)

Availability is constant here (every segment has imagery), so any v2 edge
over v1 within this subset can only come from visual content.

| Model | top 546 mi | top 589 mi |
|---|---|---|
{rows_sub}

## Reading

Reading rule set before running (module docstring): the imagery contribution
claim survives if C exceeds B citywide and v2 exceeds v1 within the observed
subset; if B alone reproduces the v2 gain, the claim must be narrowed to a
coverage effect.
"""
    (REPORTS / "imagery_ablation_report.md").write_text(report)
    print(f"Wrote {REPORTS / 'imagery_ablation_report.md'}")
    print(report)


if __name__ == "__main__":
    main()
